# Generated by Django 5.2.7 on 2025-11-04 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCita',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'INF01 - Alumno registrado en cita',
                'verbose_name_plural': 'INF01 - Alumnos registrados en citas',
                'ordering': ['curp'],
            },
        ),
        migrations.CreateModel(
            name='Asuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'CAT03 - Asunto',
                'verbose_name_plural': 'CAT03 - Asuntos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_municipio', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=80)),
                ('contador', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CAT01 - Municipio',
                'verbose_name_plural': 'CAT01 - Municipios',
                'ordering': ['cve_municipio'],
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'CAT02 - Nivel Educativo',
                'verbose_name_plural': 'CAT02 - Niveles Educativos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'CAT04 - Estatus',
                'verbose_name_plural': 'CAT04 - Estatus',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=250)),
                ('nombre_interesado', models.CharField(max_length=250)),
                ('fecha_cita', models.DateTimeField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('alumno_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.alumnocita')),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.asuntos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.municipio')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.niveleducativo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.status')),
            ],
            options={
                'verbose_name': 'INF02 - Cita',
                'verbose_name_plural': 'INF02 - Citas',
                'ordering': ['-fecha_creado'],
            },
        ),
    ]
